# Generated by Django 5.1.7 on 2025-04-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmodel",
            name="llm_provider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
